### ISSUE TITLE
Update READ.ME

### ISSUE THREAD

**Issue by TaraGijsbers** [course-dprep/ratings_series_imdb#20]

**Comment by JulianPetersIsCoding** [comment]
This issue focusses on enhancing the README.

As mentioned in the team meating we create a new file called cleaned_data.csv. In this file we have new variables and renamed variables. So to improve clarity we want to explain this under 'Explaining variables per variable dataset'. 

Hey Tara, if things remain unclear you can contact me during the day. To provide you with an example here is a link to another repository with a README I worked on: https://github.com/course-dprep/The_impact_of_Airbnb_hosts_on_guest_reviews. 

Kind regards,
Julian Peters
