### ISSUE TITLE
Code for graph

### ISSUE THREAD

**Issue by FleurdeWolf** [course-dprep/ratings_series_imdb#21]
Writing lines of code that can be used to transform our dataset into a suiting graph.

**Comment by JulianPetersIsCoding** [comment]
Hey Fleur,

I will add the file in your branche called example_analysis. Then you can use the graphs me and Iris created in the coaching session. Notice that the variables are not always the desired variables. So change this to allign it with our research purpose.

Kind regards,
Julian Peters

**Comment by JulianPetersIsCoding** [comment]
I pushed it to branche 42, because this branche is outdated and gave me extra issues to resolve.

Kind regards,
Julian Peters

**Comment by JulianPetersIsCoding** [comment]
Fleur did the work in branche 42, due to simular reasons. Therefore I close this issue. 

Kind regards,
Julian Peters
