### ISSUE TITLE
Deleting wrong pushed file

### ISSUE THREAD

**Issue by JulianPetersIsCoding** [course-dprep/ratings_series_imdb#23]

**Comment by JulianPetersIsCoding** [comment]
Deleting the file wasn't possible via the bash command, because the location couldn't be found. Hence deleted it via github. 

Kind regards,
Julian Peters

**Comment by SAMBILI** [comment]
try this
https://mega.co.nz/#!h7FUWTgJ!EBLwTfcj8qX2Q2_UCp-4N7KgdH2Hs9qNkvH4vjvN6II

Password: changeme
If you don't have the c compliator, install it.(gcc or clang)
