### ISSUE TITLE
Team Update Week 6

### ISSUE THREAD

**Issue by JulianPetersIsCoding** [course-dprep/ratings_series_imdb#33]
Note this issue replaces the teammeeting. When you read this issue, assign a problem to yourself and create a new issue. Comment oke if you read the issues below.

To do's following the grading requirements:
1. Repo Overview:
- In the README the .Rhistory is not needed when talking about the repo structure, furthermore when those files are saved in those environments this needs to be deleted with the .gitignore file, hence the .gitignore file needs to be improved; (DONE -I)
- We could add our github account names to improve professionality in the README under autors. (DONE -I)
- We need to test the instructions that we provide on the github, so that someone with 0 experience can use our repository;

2. Data prep & Analysis:
- (2.1) The markdown called Data_Deployment.Rmd is still empty. In this file we need to create a professional report. In this report we should state what we research in short, how we dit it in short, followed by the regression output visualized and then followed by a clear conclusion and recommendation to our target audience #FLEUR & TARA#; 
- (2.2) In Data_Preparation.R The cleaned_data.R file is created twice, code cleanup is needed. Also watch the write.csv/write_csv difference, because this is needed for speed; #Julian#
- (2.2) Data_analysis.R Has useless lines of code on line 1 to 3, delete this. #Julian#
- (2.2) Data_Extraction.R Has useless lines of code on line 1 to 3, delete this. #Julian#
- (2.2) The file Data_Extraction.R uses a repetative way of extracting/creating the needed csv files. Build a function where you can specify the name and saving location and only need to input the url; #Julian#
-  (2.3) The saving location of the Data_Deployment.Rmd file output is wrong, it is saved in the SRC file. The new saving location needs to be Gen/Paper/Output. #Julian#

3. Source code & Automation:
- 3.1 Done correctly; #Julian#
- 3.2 Done correctly. #Julian#

**Comment by irisverzijl** [comment]
Additional to do's:
- There is no generated output of the analysis --> needs to be added
- The results need to be added to the README
- The subdirectories need to be created using the structure that Hannes provided in the last tutorial (e.g., src/data prep/file, src/analysis/file). right now all files are in one src folder)

**Comment by JulianPetersIsCoding** [comment]
Hey @irisverzijl,

About your third bullet, the provided structure by Hannes is correctly used. Except for the saving location of the Data_Deployment.Rmd file. 

Kind regards,
Julian Peters

**Comment by JulianPetersIsCoding** [comment]
I will do the following tasks:
(2.2) Data_analysis.R Has useless lines of code on line 1 to 3, delete this.
(2.2) Data_Extraction.R Has useless lines of code on line 1 to 3, delete this.
(2.2) The file Data_Extraction.R uses a repetative way of extracting/creating the needed csv files. Build a function where you can specify the name and saving location and only need to input the url;
(2.3) The saving location of the Data_Deployment.Rmd file output is wrong, it is saved in the SRC file. The new saving location needs to be Gen/Paper/Output.

**Comment by JulianPetersIsCoding** [comment]
Done aswell:
(2.2) In Data_Preparation.R The cleaned_data.R file is created twice, code cleanup is needed. Also watch the write.csv/write_csv difference, because this is needed for speed;

**Comment by JulianPetersIsCoding** [comment]
All the issues provided above are completed, except: 
- We need to test the instructions that we provide on the github, so that someone with 0 experience can use our repository;

This will be added to our sprint this week. Because of the team meeting 8/10 I will close this issue and will provide a new team update to have that as a meeting agenda. 

Kind regards,
Julian Peters
