### ISSUE TITLE
Data deployment

### ISSUE THREAD

**Issue by irisverzijl** [course-dprep/ratings_series_imdb#41]
The markdown called Data_Deployment.Rmd is still empty. 
In this file we need to create a professional/publication-ready report. In this report we should state what we research in short, how we did it in short, followed by the regression output visualized and then followed by a clear conclusion and recommendation to our target audience;

- Research motivation
- Research Method
- Results
- Theoretical / Practical Implications
- conlusion 

beetje structuur aanhouden van een research proposal maar dan met conclusie en implications. voor figuren contact Julian.
ongeveer 2 pagina's 

deadline = vrijdag

**Comment by FleurdeWolf** [comment]
Finished the data deployment with the graphs, plot, regression and the conclusion.
